name: falles
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - folium
  - streamlit
  - streamlit-folium
  - pillow
  - requests
  - shapely
  - pyproj
  - pyarrow
  - ortools
  - pip:
      - absl-py
      - altair
      - beautifulsoup4
      - branca
      - cachetools
      - certifi
      - click
      - contourpy
      - cycler
      - fonttools
      - gitdb
      - gitpython
      - greenlet
      - h11
      - idna
      - immutabledict
      - jinja2
      - jsonschema
      - kiwisolver
      - markdown-it-py
      - markupsafe
      - mdurl
      - more-itertools
      - narwhals
      - outcome
      - playwright
      - protobuf
      - pydeck
      - pyee
      - pyogrio
      - pyparsing
      - pysocks
      - pytz
      - referencing
      - rich
      - rpds-py
      - selenium
      - smmap
      - sniffio
      - sortedcontainers
      - soupsieve
      - tenacity
      - toml
      - tqdm
      - trio
      - trio-websocket
      - tzdata
      - urllib3
      - watchdog
      - websocket-client
      - wsproto
      - xyzservices